### ISSUE TITLE
Typo in definition of dataMomentW (Eval.jl)

### ISSUE THREAD

**Issue by gregobad** [floswald/SMM.jl#44]
Line 197 of Eval.jl is currently:

`dataMomentW(ev::Eval) = dataMomentW(ev,collect(keys(ev.dataMomentW)))`

When called, this function produces the error 

`ERROR: type Eval has no field dataMomentW
Stacktrace:`
` [1] getproperty(::Any, ::Symbol) at ./Base.jl:20`
` [2] dataMomentW(::SMM.Eval) at /home/gregorymartin/.julia/packages/SMM/MDWS3/src/mopt/Eval.jl:197`
` [3] top-level scope at none:0`

The field is `dataMomentsW` rather than `dataMomentW`. Corrected version:

`dataMomentW(ev::Eval) = dataMomentW(ev,collect(keys(ev.dataMomentsW)))`

**Comment by floswald** [comment]
Thanks! Can you submit a PR with that correction? (Can guide if you want)
Cheers

**Comment by gregobad** [comment]
Just submitted a pull request.
